travis:
  secure:
    BINSTAR_TOKEN: V/MH7Qg1yopA28iuQ6oaXpPit2sHLOdIY22DQ8AWgTcJAmNweUuIyuONf5jC5lIeNFylMmc9aW7rV++wMt2rPOEgRiydBcs4hhIkFyeZkMOP1FsAQCWbWU2nfu7AYR0TYvpbn26iBNC3pjTT+TzZzEN1B/4eexsdwTHw7FtFNyL6nXzLMU07IVWbBOt7IZDy/D+BIWgJSUGS0A+kaAYy+AMgxGCH69V4A8qr6WLlb5I2VRkJ23Y8CMc9s+qntIkMGXnCUHekQURK79jxAqOWHVQRntDvp2NIFXUcvEQ33XN8L6dVPC3kni6dIclkW8vKJvHsO0GfwjG20UejAkAClVxvvtM2yHJVyiJ6ufpnaK0DReHhHL64bq68HDWvFBagGjp9jx8kzaxG+KQi7QbtA3VDp5I7oK2ipQwRDsvN3wyeLvdLj6J7UrI1w0W1QTvQAGnd/BFNluwiHs7A6mD8/fghH6AWO+eZNJ4Cuhp+IqTBILJDMIIY7EIiB0Ubnmgm6vr8wAJPIft8MIIEvWNA9K5PfpaS0HR5H6KopapDbCG6ZcOfZkaTG80XA/nmxsSxt28Ys4TIKhRjEGtE161p4UNgMx26ujDNPa7szoOBayRVHOzhNr6ZkDMuM8KUidQ59MBaora1wb9P1Q6fXx49Tas9IkShAzEaBubuevz7rek=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
